
"use client";

import { AlertCircle } from "lucide-react";
import { ToolErrorModal } from "./ToolErrorModal";

interface AIDisclaimerProps {
  toolId: string;
  toolName: string;
}

export function AIDisclaimer({ toolId, toolName }: AIDisclaimerProps) {
  return (
    <div className="bg-amber-50/90 backdrop-blur border border-amber-200 p-4 rounded-xl flex flex-col sm:flex-row items-center justify-between gap-4 text-slate-700 text-sm font-medium transition-all my-6 shadow-sm">
      <div className="flex items-start gap-3 flex-1">
        <AlertCircle className="w-5 h-5 text-amber-500 mt-0.5 shrink-0" />
        <p className="leading-relaxed text-[13px] text-left">
          ⚠️ Notice: Initial evaluations are automatically generated by AI for rapid directory categorization and may contain errors. Please review carefully. Human administrators manually review all final entries.
        </p>
      </div>
      <ToolErrorModal toolId={toolId} toolName={toolName} />
    </div>
  );
}
